// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/pengiriman/pengiriman.proto

package pengiriman

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pengiriman struct {
	UUID                 string       `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Desc                 string       `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Weigth               int32        `protobuf:"varint,3,opt,name=weigth,proto3" json:"weigth,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	DriverId             string       `protobuf:"bytes,5,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Pengiriman) Reset()         { *m = Pengiriman{} }
func (m *Pengiriman) String() string { return proto.CompactTextString(m) }
func (*Pengiriman) ProtoMessage()    {}
func (*Pengiriman) Descriptor() ([]byte, []int) {
	return fileDescriptor_5489ba00305b307b, []int{0}
}

func (m *Pengiriman) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pengiriman.Unmarshal(m, b)
}
func (m *Pengiriman) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pengiriman.Marshal(b, m, deterministic)
}
func (m *Pengiriman) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pengiriman.Merge(m, src)
}
func (m *Pengiriman) XXX_Size() int {
	return xxx_messageInfo_Pengiriman.Size(m)
}
func (m *Pengiriman) XXX_DiscardUnknown() {
	xxx_messageInfo_Pengiriman.DiscardUnknown(m)
}

var xxx_messageInfo_Pengiriman proto.InternalMessageInfo

func (m *Pengiriman) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Pengiriman) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Pengiriman) GetWeigth() int32 {
	if m != nil {
		return m.Weigth
	}
	return 0
}

func (m *Pengiriman) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Pengiriman) GetDriverId() string {
	if m != nil {
		return m.DriverId
	}
	return ""
}

type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PelangganId          string   `protobuf:"bytes,2,opt,name=pelanggan_id,json=pelangganId,proto3" json:"pelanggan_id,omitempty"`
	Alamat               string   `protobuf:"bytes,3,opt,name=alamat,proto3" json:"alamat,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_5489ba00305b307b, []int{1}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetPelangganId() string {
	if m != nil {
		return m.PelangganId
	}
	return ""
}

func (m *Container) GetAlamat() string {
	if m != nil {
		return m.Alamat
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

//buat model kosong sebagi penampung
// dataRequest yg didaftarkan pada method grpc
type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5489ba00305b307b, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type Response struct {
	Created    bool        `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Pengiriman *Pengiriman `protobuf:"bytes,2,opt,name=pengiriman,proto3" json:"pengiriman,omitempty"`
	//tambahkan slice/array untuk menampung bermacam-macam pengiriman
	Pengiriman2          []*Pengiriman `protobuf:"bytes,3,rep,name=pengiriman2,proto3" json:"pengiriman2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5489ba00305b307b, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetPengiriman() *Pengiriman {
	if m != nil {
		return m.Pengiriman
	}
	return nil
}

func (m *Response) GetPengiriman2() []*Pengiriman {
	if m != nil {
		return m.Pengiriman2
	}
	return nil
}

func init() {
	proto.RegisterType((*Pengiriman)(nil), "pengiriman.Pengiriman")
	proto.RegisterType((*Container)(nil), "pengiriman.Container")
	proto.RegisterType((*GetRequest)(nil), "pengiriman.GetRequest")
	proto.RegisterType((*Response)(nil), "pengiriman.Response")
}

func init() {
	proto.RegisterFile("proto/pengiriman/pengiriman.proto", fileDescriptor_5489ba00305b307b)
}

var fileDescriptor_5489ba00305b307b = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x4b, 0xeb, 0x40,
	0x10, 0xc7, 0x5f, 0xfa, 0x3b, 0x93, 0x52, 0xde, 0x1b, 0x9e, 0x35, 0xe8, 0xa5, 0xcd, 0xa9, 0xa7,
	0x0a, 0x11, 0xc5, 0xa3, 0x58, 0xa1, 0xe4, 0x26, 0x2b, 0x3d, 0xcb, 0x9a, 0x1d, 0xe2, 0x42, 0xbb,
	0x89, 0x9b, 0x6d, 0xfd, 0x4f, 0x04, 0x6f, 0xfe, 0xa9, 0x92, 0x4d, 0xdb, 0xac, 0x87, 0xde, 0xe6,
	0xfb, 0x9d, 0x1f, 0xfb, 0x99, 0x49, 0x60, 0x5a, 0xe8, 0xdc, 0xe4, 0x57, 0x05, 0xa9, 0x4c, 0x6a,
	0xb9, 0xe1, 0xca, 0x09, 0xe7, 0x36, 0x87, 0xd0, 0x38, 0xd1, 0xb7, 0x07, 0xf0, 0x74, 0x94, 0x88,
	0xd0, 0x59, 0xad, 0x92, 0xc7, 0xd0, 0x9b, 0x78, 0x33, 0x9f, 0xd9, 0xb8, 0xf2, 0x04, 0x95, 0x69,
	0xd8, 0xaa, 0xbd, 0x2a, 0xc6, 0x31, 0xf4, 0x3e, 0x48, 0x66, 0xe6, 0x2d, 0x6c, 0x4f, 0xbc, 0x59,
	0x97, 0xed, 0x15, 0xde, 0x00, 0xa4, 0xb9, 0x32, 0x5c, 0x2a, 0xd2, 0x65, 0xd8, 0x99, 0xb4, 0x67,
	0x41, 0x7c, 0x36, 0x77, 0x08, 0x16, 0x87, 0x2c, 0x73, 0x0a, 0xf1, 0x12, 0x7c, 0xa1, 0xe5, 0x8e,
	0xf4, 0x8b, 0x14, 0x61, 0xd7, 0xbe, 0x33, 0xa8, 0x8d, 0x44, 0x44, 0x39, 0xf8, 0xc7, 0x2e, 0x1c,
	0x41, 0x4b, 0x8a, 0x3d, 0x5e, 0x4b, 0x0a, 0x9c, 0xc2, 0xb0, 0xa0, 0x35, 0x57, 0x59, 0xc6, 0x55,
	0xd5, 0x5c, 0x43, 0x06, 0x47, 0x2f, 0x11, 0x15, 0x2b, 0x5f, 0xf3, 0x0d, 0x37, 0x96, 0xd5, 0x67,
	0x7b, 0x85, 0xe7, 0xd0, 0xdf, 0x96, 0xf5, 0x93, 0x9d, 0x3a, 0x51, 0xc9, 0x44, 0x44, 0x43, 0x80,
	0x25, 0x19, 0x46, 0xef, 0x5b, 0x2a, 0x4d, 0xf4, 0xe9, 0xc1, 0x80, 0x51, 0x59, 0xe4, 0xaa, 0x24,
	0x0c, 0xa1, 0x9f, 0x6a, 0xe2, 0x86, 0x6a, 0x86, 0x01, 0x3b, 0x48, 0xbc, 0x05, 0xe7, 0xac, 0x16,
	0x23, 0x88, 0xc7, 0xee, 0xe6, 0xcd, 0x95, 0x99, 0x53, 0x89, 0x77, 0x10, 0x34, 0x2a, 0x0e, 0xdb,
	0xf6, 0x64, 0xa7, 0x1a, 0xdd, 0xd2, 0xf8, 0xcb, 0x83, 0x7f, 0x4d, 0xee, 0x99, 0xf4, 0x4e, 0xa6,
	0x84, 0x0f, 0xf0, 0x77, 0x61, 0x91, 0x9c, 0xaf, 0x7a, 0x62, 0xdc, 0xc5, 0x7f, 0xd7, 0x3f, 0xec,
	0x18, 0xfd, 0xc1, 0x7b, 0x18, 0x2d, 0xc9, 0x34, 0x85, 0xf1, 0xef, 0x09, 0xcd, 0x71, 0x4e, 0x4d,
	0x78, 0xed, 0xd9, 0x3f, 0xed, 0xfa, 0x27, 0x00, 0x00, 0xff, 0xff, 0xde, 0x0e, 0x37, 0xfc, 0x8e,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PengirimanServiceClient is the client API for PengirimanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PengirimanServiceClient interface {
	//mendaftarkan method CreatePengiriman untuk MEMBUAT PENGIRIMAN
	CreatePengiriman(ctx context.Context, in *Pengiriman, opts ...grpc.CallOption) (*Response, error)
	GetPengiriman2(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error)
}

type pengirimanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPengirimanServiceClient(cc grpc.ClientConnInterface) PengirimanServiceClient {
	return &pengirimanServiceClient{cc}
}

func (c *pengirimanServiceClient) CreatePengiriman(ctx context.Context, in *Pengiriman, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pengiriman.PengirimanService/CreatePengiriman", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pengirimanServiceClient) GetPengiriman2(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pengiriman.PengirimanService/GetPengiriman2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PengirimanServiceServer is the server API for PengirimanService service.
type PengirimanServiceServer interface {
	//mendaftarkan method CreatePengiriman untuk MEMBUAT PENGIRIMAN
	CreatePengiriman(context.Context, *Pengiriman) (*Response, error)
	GetPengiriman2(context.Context, *GetRequest) (*Response, error)
}

// UnimplementedPengirimanServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPengirimanServiceServer struct {
}

func (*UnimplementedPengirimanServiceServer) CreatePengiriman(ctx context.Context, req *Pengiriman) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePengiriman not implemented")
}
func (*UnimplementedPengirimanServiceServer) GetPengiriman2(ctx context.Context, req *GetRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPengiriman2 not implemented")
}

func RegisterPengirimanServiceServer(s *grpc.Server, srv PengirimanServiceServer) {
	s.RegisterService(&_PengirimanService_serviceDesc, srv)
}

func _PengirimanService_CreatePengiriman_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pengiriman)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PengirimanServiceServer).CreatePengiriman(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pengiriman.PengirimanService/CreatePengiriman",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PengirimanServiceServer).CreatePengiriman(ctx, req.(*Pengiriman))
	}
	return interceptor(ctx, in, info, handler)
}

func _PengirimanService_GetPengiriman2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PengirimanServiceServer).GetPengiriman2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pengiriman.PengirimanService/GetPengiriman2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PengirimanServiceServer).GetPengiriman2(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PengirimanService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pengiriman.PengirimanService",
	HandlerType: (*PengirimanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePengiriman",
			Handler:    _PengirimanService_CreatePengiriman_Handler,
		},
		{
			MethodName: "GetPengiriman2",
			Handler:    _PengirimanService_GetPengiriman2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pengiriman/pengiriman.proto",
}
