// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/pengiriman/pengiriman.proto

package pengiriman

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pengiriman struct {
	UUID                 string       `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Desc                 string       `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Weigth               int32        `protobuf:"varint,3,opt,name=weigth,proto3" json:"weigth,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	DriverId             string       `protobuf:"bytes,5,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Pengiriman) Reset()         { *m = Pengiriman{} }
func (m *Pengiriman) String() string { return proto.CompactTextString(m) }
func (*Pengiriman) ProtoMessage()    {}
func (*Pengiriman) Descriptor() ([]byte, []int) {
	return fileDescriptor_5489ba00305b307b, []int{0}
}

func (m *Pengiriman) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pengiriman.Unmarshal(m, b)
}
func (m *Pengiriman) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pengiriman.Marshal(b, m, deterministic)
}
func (m *Pengiriman) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pengiriman.Merge(m, src)
}
func (m *Pengiriman) XXX_Size() int {
	return xxx_messageInfo_Pengiriman.Size(m)
}
func (m *Pengiriman) XXX_DiscardUnknown() {
	xxx_messageInfo_Pengiriman.DiscardUnknown(m)
}

var xxx_messageInfo_Pengiriman proto.InternalMessageInfo

func (m *Pengiriman) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Pengiriman) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Pengiriman) GetWeigth() int32 {
	if m != nil {
		return m.Weigth
	}
	return 0
}

func (m *Pengiriman) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Pengiriman) GetDriverId() string {
	if m != nil {
		return m.DriverId
	}
	return ""
}

type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PelangganId          string   `protobuf:"bytes,2,opt,name=pelanggan_id,json=pelangganId,proto3" json:"pelanggan_id,omitempty"`
	Alamat               string   `protobuf:"bytes,3,opt,name=alamat,proto3" json:"alamat,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_5489ba00305b307b, []int{1}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetPelangganId() string {
	if m != nil {
		return m.PelangganId
	}
	return ""
}

func (m *Container) GetAlamat() string {
	if m != nil {
		return m.Alamat
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Response struct {
	Created              bool        `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Pengiriman           *Pengiriman `protobuf:"bytes,2,opt,name=pengiriman,proto3" json:"pengiriman,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5489ba00305b307b, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetPengiriman() *Pengiriman {
	if m != nil {
		return m.Pengiriman
	}
	return nil
}

func init() {
	proto.RegisterType((*Pengiriman)(nil), "pengiriman.Pengiriman")
	proto.RegisterType((*Container)(nil), "pengiriman.Container")
	proto.RegisterType((*Response)(nil), "pengiriman.Response")
}

func init() {
	proto.RegisterFile("proto/pengiriman/pengiriman.proto", fileDescriptor_5489ba00305b307b)
}

var fileDescriptor_5489ba00305b307b = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0xcb, 0x4e, 0xc3, 0x30,
	0x10, 0x24, 0x7d, 0x67, 0x8b, 0x10, 0xac, 0xa0, 0x58, 0x70, 0x69, 0x73, 0xea, 0xa9, 0x48, 0x41,
	0xf0, 0x01, 0x94, 0x4b, 0x6e, 0xc8, 0xa8, 0xe2, 0x82, 0x84, 0x4c, 0xbc, 0x0a, 0x96, 0x5a, 0x27,
	0x72, 0x42, 0xf9, 0x1d, 0x3e, 0x15, 0xc5, 0xce, 0xc3, 0x17, 0x6e, 0x3b, 0x33, 0xde, 0x9d, 0xf1,
	0x2e, 0xac, 0x0a, 0x93, 0x57, 0xf9, 0x5d, 0x41, 0x3a, 0x53, 0x46, 0x1d, 0x84, 0xf6, 0xca, 0x8d,
	0xd5, 0x10, 0x7a, 0x26, 0xfa, 0x0d, 0x00, 0x5e, 0x3a, 0x88, 0x08, 0xa3, 0xdd, 0x2e, 0x79, 0x66,
	0xc1, 0x32, 0x58, 0x87, 0xdc, 0xd6, 0x35, 0x27, 0xa9, 0x4c, 0xd9, 0xc0, 0x71, 0x75, 0x8d, 0x0b,
	0x98, 0xfc, 0x90, 0xca, 0xaa, 0x2f, 0x36, 0x5c, 0x06, 0xeb, 0x31, 0x6f, 0x10, 0x3e, 0x00, 0xa4,
	0xb9, 0xae, 0x84, 0xd2, 0x64, 0x4a, 0x36, 0x5a, 0x0e, 0xd7, 0xf3, 0xf8, 0x6a, 0xe3, 0x25, 0xd8,
	0xb6, 0x2a, 0xf7, 0x1e, 0xe2, 0x2d, 0x84, 0xd2, 0xa8, 0x23, 0x99, 0x0f, 0x25, 0xd9, 0xd8, 0xfa,
	0xcc, 0x1c, 0x91, 0xc8, 0x28, 0x87, 0xb0, 0xeb, 0xc2, 0x33, 0x18, 0x28, 0xd9, 0xc4, 0x1b, 0x28,
	0x89, 0x2b, 0x38, 0x2d, 0x68, 0x2f, 0x74, 0x96, 0x09, 0x5d, 0x37, 0xbb, 0x90, 0xf3, 0x8e, 0x4b,
	0x64, 0x9d, 0x55, 0xec, 0xc5, 0x41, 0x54, 0x36, 0x6b, 0xc8, 0x1b, 0x84, 0xd7, 0x30, 0xfd, 0x2e,
	0x9d, 0xe5, 0xc8, 0x09, 0x35, 0x4c, 0x64, 0xf4, 0x0e, 0x33, 0x4e, 0x65, 0x91, 0xeb, 0x92, 0x90,
	0xc1, 0x34, 0x35, 0x24, 0x2a, 0x72, 0xa6, 0x33, 0xde, 0x42, 0x7c, 0x04, 0x6f, 0x8f, 0xd6, 0x77,
	0x1e, 0x2f, 0xfc, 0xaf, 0xf6, 0x6b, 0xe5, 0xde, 0xcb, 0xf8, 0x0d, 0x2e, 0x7a, 0xe5, 0x95, 0xcc,
	0x51, 0xa5, 0x84, 0x4f, 0x70, 0xbe, 0xb5, 0x73, 0xbd, 0x5b, 0xfc, 0x33, 0xec, 0xe6, 0xd2, 0xe7,
	0xdb, 0xa0, 0xd1, 0xc9, 0xe7, 0xc4, 0x5e, 0xf7, 0xfe, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x7e,
	0x31, 0xe8, 0x02, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PengirimanServiceClient is the client API for PengirimanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PengirimanServiceClient interface {
	CreatePengiriman(ctx context.Context, in *Pengiriman, opts ...grpc.CallOption) (*Response, error)
}

type pengirimanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPengirimanServiceClient(cc grpc.ClientConnInterface) PengirimanServiceClient {
	return &pengirimanServiceClient{cc}
}

func (c *pengirimanServiceClient) CreatePengiriman(ctx context.Context, in *Pengiriman, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pengiriman.PengirimanService/CreatePengiriman", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PengirimanServiceServer is the server API for PengirimanService service.
type PengirimanServiceServer interface {
	CreatePengiriman(context.Context, *Pengiriman) (*Response, error)
}

// UnimplementedPengirimanServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPengirimanServiceServer struct {
}

func (*UnimplementedPengirimanServiceServer) CreatePengiriman(ctx context.Context, req *Pengiriman) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePengiriman not implemented")
}

func RegisterPengirimanServiceServer(s *grpc.Server, srv PengirimanServiceServer) {
	s.RegisterService(&_PengirimanService_serviceDesc, srv)
}

func _PengirimanService_CreatePengiriman_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pengiriman)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PengirimanServiceServer).CreatePengiriman(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pengiriman.PengirimanService/CreatePengiriman",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PengirimanServiceServer).CreatePengiriman(ctx, req.(*Pengiriman))
	}
	return interceptor(ctx, in, info, handler)
}

var _PengirimanService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pengiriman.PengirimanService",
	HandlerType: (*PengirimanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePengiriman",
			Handler:    _PengirimanService_CreatePengiriman_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pengiriman/pengiriman.proto",
}
